general:
  maven:
    projectSettingsFile: 'mysettings.xml'
steps:
  githubPublishRelease:
    addClosedIssues: true
    addDeltaToLastRelease: true
    excludeLabels:
      - 'discussion'
      - 'duplicate'
      - 'invalid'
      - 'question'
      - 'wontfix'
    owner: 'SAP'
    repository: 'jenkins-library'
    releaseBodyHeader: ''
  githubCreatePullRequest:
    base: master
    owner: 'SAP'
    repository: 'jenkins-library'
    labels:
      - 'REVIEW'
      - 'go-piper'
    assignees:
      - 'marcusholl'
      - 'daniel-kurzynski'
      - 'fwilhe'
      - 'CCFenner'
      - 'OliverNocon'
      - 'nevskrem'
  cloudFoundryDeploy:
    org: myOrg
    space: myspace12345
    mtaExtensionCredentials:
        brokerCredentialsHash: 'EDOM_RETAILER_DEV_SBF_HASH'
        dummy: 'xxxxx'
